FROM python:3.8.13-slim-bullseye
WORKDIR /app
COPY . /app/
RUN mkdir -p /app/data && \
    ./patch_no_tensorflow.sh && \
    pip install -r /app/requirements.txt
EXPOSE 5000
ENV PASTEY_DATA_DIRECTORY=/app/data  
CMD ["python3", "app.py"]
